# Dependencies
markdown:         kramdown
#pygments:         true
Rouge:         true

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            And now for something completely different
tagline:          Bean Dip!
url:              http://weaselpipe.com #http://mrdanbrooks.github.io
paginate:         5
#baseurl:          http://weaselpipe.com/ #http://mrdanbrooks.github.io/
author:
  name:           Dan Brooks
  url:            http://danbrooks.net
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mrdanbrooks/mrdanbrooks.github.io
gems: [jekyll-paginate]
