# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            And now for something completely different
tagline:          Bean Dip!
url:              http://danbrooks.info
paginate:         1
baseurl:          /
author:
  name:           Dan Brooks
  url:            http://danbrooks.net
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/mrdanbrooks/mrdanbrooks.github.io

gems: [tag_gen]
